### ISSUE TITLE
Return statement does nothing

### ISSUE THREAD

**Issue by fmaussion** [ASPP/pelita-player-2018-melbourne#3]
In [this line](https://github.com/ASPP/pelita-player-2018-melbourne/blob/f386c63ff7303bec5d47c6dc15cbb82a50423bbd/team/demo_player.py#L37) the method return a move but this is not used afterwards.

**Comment by Debilski** [comment]
Good find. I even remember wondering why it would not stop last time I showed a demo of this. :)
